 
export AWS_ACCESS_KEY_ID=1234567890
export AWS_SECRET_ACCESS_KEY=ABCDEFGHIJKLMN
export AWS_DEFAULT_REGION=us-east-1
export AWS_DEFAULT_OUTPUT=text

export AWS_ACCOUNT_ID=1234567890
export AWS_REGION=$AWS_DEFAULT_REGION